#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""adc-midi-split.py 260818b

Split selected drum-pattern ranges from original MIDI files according to an
ADC PatternLab CSV.

Inputs
------
1. One original MIDI file, or a directory containing original MIDI files
2. Reviewed PatternLab CSV generated by adc-patternlab.py
3. slot_map_definitions.json (default: beside this script)

Behavior:
    - File input: process only CSV rows whose FILE matches that MIDI filename.
    - Directory input: process all EXPORT=YES CSV rows and locate each source
      MIDI by filename in that directory.
    - By default, save one CH10 MIDI file per EXPORT=YES row.
    - Use --dry-run to validate inputs and print the split plan without writing
      any files.

The script performs no genre, subdivision, name, duplicate, or slot-map
inference. Those decisions are taken directly from the reviewed CSV.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import mido
from mido import Message, MetaMessage, MidiFile, MidiTrack


SCRIPT_NAME = "adc-midi-split.py"
VERSION = "260818b"
VERSION_TEXT = f"{SCRIPT_NAME} {VERSION}"

REQUIRED_COLUMNS = {
    "FILE",
    "START_BAR",
    "END_BAR",
    "NAME",
    "TIME_SIG",
    "SLOT_MAP",
    "EXPORT",
    "SUBDIV",
    "SOURCE",
}
VALID_SUBDIV = {"16", "32", "8T", "16T"}
NAME_RE = re.compile(r"^[A-Z0-9]{3}_[0-9]{4}$")




@dataclass(frozen=True)
class SlotDefinition:
    index: int
    abbrev: str
    extended: str
    representative_midi: int
    allowed_notes: Tuple[int, ...]


@dataclass(frozen=True)
class SlotMapDefinition:
    map_id: int
    name: str
    slots: Tuple[SlotDefinition, ...]

    @property
    def accepted_notes(self) -> Set[int]:
        out: Set[int] = set()
        for slot in self.slots:
            out.update(slot.allowed_notes)
        return out

    def slot_for_note(self, note: int) -> Optional[int]:
        for slot in self.slots:
            if note in slot.allowed_notes:
                return slot.index
        return None


@dataclass(frozen=True)
class PatternSpec:
    row_number: int
    file: str
    start_bar: int
    end_bar: int
    name: str
    time_sig: str
    slot_map: str
    export: bool
    genre: str
    subdiv: str
    orn: bool
    duplicate_of: str
    source: str


@dataclass(frozen=True)
class BarInfo:
    number: int
    start_tick: int
    end_tick: int
    numerator: int
    denominator: int


@dataclass(frozen=True)
class AbsoluteEvent:
    tick: int
    order: int
    message: Message | MetaMessage


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------


def fail(message: str) -> "NoReturn":
    raise SystemExit(f"[ERROR] {message}")


def parse_yes_no(value: str, *, field: str, row_number: int) -> bool:
    normalized = value.strip().upper()
    if normalized == "YES":
        return True
    if normalized == "NO":
        return False
    fail(f"CSV row {row_number}: {field} must be YES or NO, got {value!r}")


def parse_time_signature(value: str, *, row_number: int) -> Tuple[int, int]:
    m = re.fullmatch(r"([1-9][0-9]*)/([1-9][0-9]*)", value.strip())
    if not m:
        fail(f"CSV row {row_number}: invalid TIME_SIG {value!r}")
    num, den = int(m.group(1)), int(m.group(2))
    if den & (den - 1):
        fail(f"CSV row {row_number}: TIME_SIG denominator must be a power of two: {value!r}")
    return num, den


def safe_output_stem(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("._") or "patterns"




# ---------------------------------------------------------------------------
# Slot-map JSON
# ---------------------------------------------------------------------------


def load_slot_maps(path: Path) -> Dict[str, SlotMapDefinition]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"slot-map definition not found: {path}")
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read slot-map definition {path}: {exc}")

    if not isinstance(data, list) or not data:
        fail("slot-map JSON root must be a non-empty array")

    maps: Dict[str, SlotMapDefinition] = {}
    ids: Set[int] = set()
    for item in data:
        if not isinstance(item, dict):
            fail("each slot-map JSON entry must be an object")
        map_id = item.get("slot_map_id")
        name = item.get("name")
        slots_data = item.get("slots")
        if not isinstance(map_id, int) or map_id in ids:
            fail(f"invalid or duplicate slot_map_id: {map_id!r}")
        if not isinstance(name, str) or not name.strip() or name in maps:
            fail(f"invalid or duplicate slot-map name: {name!r}")
        if not isinstance(slots_data, list) or not slots_data:
            fail(f"slot map {name}: slots must be a non-empty list")

        parsed_slots: List[SlotDefinition] = []
        seen_indices: Set[int] = set()
        for raw in slots_data:
            if not isinstance(raw, dict):
                fail(f"slot map {name}: every slot must be an object")
            index = raw.get("slot")
            abbrev = raw.get("abbrev")
            extended = raw.get("extended", abbrev)
            representative = raw.get("representative_midi")
            allowed = raw.get("midi_input_allowed")
            if not isinstance(index, int) or index in seen_indices:
                fail(f"slot map {name}: invalid or duplicate slot number {index!r}")
            if not isinstance(abbrev, str) or not abbrev.strip():
                fail(f"slot map {name}, slot {index}: missing abbrev")
            if not isinstance(extended, str) or not extended.strip():
                fail(f"slot map {name}, slot {index}: missing extended name")
            if not isinstance(representative, int):
                fail(f"slot map {name}, slot {index}: invalid representative_midi")
            if not isinstance(allowed, list) or not allowed or any(not isinstance(n, int) for n in allowed):
                fail(f"slot map {name}, slot {index}: invalid midi_input_allowed")
            if representative not in allowed:
                fail(f"slot map {name}, slot {index}: representative_midi must be allowed")
            seen_indices.add(index)
            parsed_slots.append(
                SlotDefinition(
                    index=index,
                    abbrev=abbrev.strip(),
                    extended=extended.strip(),
                    representative_midi=representative,
                    allowed_notes=tuple(allowed),
                )
            )

        parsed_slots.sort(key=lambda slot: slot.index)
        expected = list(range(len(parsed_slots)))
        actual = [slot.index for slot in parsed_slots]
        if actual != expected:
            fail(f"slot map {name}: slot numbers must be contiguous 0..{len(parsed_slots)-1}")

        ids.add(map_id)
        maps[name] = SlotMapDefinition(map_id, name, tuple(parsed_slots))

    return maps


# ---------------------------------------------------------------------------
# PatternLab CSV
# ---------------------------------------------------------------------------


def load_pattern_csv(path: Path) -> List[PatternSpec]:
    try:
        handle = path.open("r", encoding="utf-8-sig", newline="")
    except OSError as exc:
        fail(f"cannot open CSV {path}: {exc}")

    with handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            fail(f"CSV has no header: {path}")
        normalized_fields = [str(field).strip().upper() for field in reader.fieldnames]
        missing = sorted(REQUIRED_COLUMNS - set(normalized_fields))
        if missing:
            fail(f"CSV missing required column(s): {', '.join(missing)}")
        reader.fieldnames = normalized_fields

        specs: List[PatternSpec] = []
        for row_number, raw in enumerate(reader, start=2):
            if raw is None or not any(str(v or "").strip() for v in raw.values()):
                continue
            row = {str(k).strip().upper(): str(v or "").strip() for k, v in raw.items() if k is not None}
            try:
                start_bar = int(row.get("START_BAR", ""))
                end_bar = int(row.get("END_BAR", ""))
            except ValueError:
                fail(f"CSV row {row_number}: START_BAR and END_BAR must be integers")
            if start_bar < 1 or end_bar < start_bar:
                fail(f"CSV row {row_number}: invalid bar range {start_bar}-{end_bar}")

            export = parse_yes_no(row.get("EXPORT", ""), field="EXPORT", row_number=row_number)

            name = row.get("NAME", "").upper()
            if export:
                if not NAME_RE.fullmatch(name):
                    fail(
                        f"CSV row {row_number}: NAME must match ABC_0001 "
                        f"for EXPORT=YES, got {name!r}"
                    )
            elif name and not NAME_RE.fullmatch(name):
                fail(
                    f"CSV row {row_number}: non-empty NAME must match ABC_0001, "
                    f"got {name!r}"
                )

            time_sig = row.get("TIME_SIG", "")
            parse_time_signature(time_sig, row_number=row_number)

            subdiv = row.get("SUBDIV", "").upper()
            if subdiv not in VALID_SUBDIV:
                fail(f"CSV row {row_number}: SUBDIV must be one of 16, 32, 8T, 16T, got {subdiv!r}")

            orn_raw = row.get("ORN", "NO") or "NO"
            orn = parse_yes_no(orn_raw, field="ORN", row_number=row_number)

            specs.append(
                PatternSpec(
                    row_number=row_number,
                    file=row.get("FILE", ""),
                    start_bar=start_bar,
                    end_bar=end_bar,
                    name=name,
                    time_sig=time_sig,
                    slot_map=row.get("SLOT_MAP", ""),
                    export=export,
                    genre=row.get("GENRE", "").upper(),
                    subdiv=subdiv,
                    orn=orn,
                    duplicate_of=row.get("DUPLICATE_OF", ""),
                    source=row.get("SOURCE", ""),
                )
            )

    if not specs:
        fail("CSV contains no pattern rows")
    return specs


# ---------------------------------------------------------------------------
# MIDI reading and bar map
# ---------------------------------------------------------------------------


def merged_absolute_events(mid: MidiFile) -> List[AbsoluteEvent]:
    merged = mido.merge_tracks(mid.tracks) if mid.type == 1 else mid.tracks[0]
    events: List[AbsoluteEvent] = []
    tick = 0
    for order, msg in enumerate(merged):
        tick += msg.time
        events.append(AbsoluteEvent(tick, order, msg.copy(time=0)))
    return events


def collect_time_signatures(events: Sequence[AbsoluteEvent]) -> List[Tuple[int, int, int]]:
    values: Dict[int, Tuple[int, int]] = {0: (4, 4)}
    for event in events:
        msg = event.message
        if isinstance(msg, MetaMessage) and msg.type == "time_signature":
            values[event.tick] = (int(msg.numerator), int(msg.denominator))
    return [(tick, num, den) for tick, (num, den) in sorted(values.items())]


def build_bar_map(tpq: int, time_signatures: Sequence[Tuple[int, int, int]], total_tick: int) -> List[BarInfo]:
    if tpq <= 0:
        fail(f"invalid ticks_per_beat: {tpq}")
    if total_tick <= 0:
        fail("MIDI contains no timed content")

    bars: List[BarInfo] = []
    ts_index = 0
    tick = 0
    number = 1
    while tick < total_tick:
        while ts_index + 1 < len(time_signatures) and time_signatures[ts_index + 1][0] <= tick:
            ts_index += 1
        _, num, den = time_signatures[ts_index]
        nominal_end = tick + max(1, round(tpq * num * 4 / den))
        if ts_index + 1 < len(time_signatures):
            next_change = time_signatures[ts_index + 1][0]
            if tick < next_change < nominal_end:
                nominal_end = next_change
        bars.append(BarInfo(number, tick, nominal_end, num, den))
        tick = nominal_end
        number += 1
    return bars


def active_meta_before(events: Sequence[AbsoluteEvent], start_tick: int) -> Tuple[Tuple[int, int], int]:
    time_sig = (4, 4)
    tempo = 500000
    for event in events:
        if event.tick > start_tick:
            break
        msg = event.message
        if isinstance(msg, MetaMessage):
            if msg.type == "time_signature":
                time_sig = (int(msg.numerator), int(msg.denominator))
            elif msg.type == "set_tempo":
                tempo = int(msg.tempo)
    return time_sig, tempo


def drum_note_ons(events: Sequence[AbsoluteEvent], start_tick: int, end_tick: int) -> List[AbsoluteEvent]:
    return [
        event
        for event in events
        if start_tick <= event.tick < end_tick
        and isinstance(event.message, Message)
        and getattr(event.message, "channel", -1) == 9
        and event.message.type == "note_on"
        and event.message.velocity > 0
    ]


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_specs(
    specs: Sequence[PatternSpec],
    input_midi: Path,
    slot_maps: Dict[str, SlotMapDefinition],
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
) -> List[PatternSpec]:
    """Validate EXPORT=YES rows already selected for one source MIDI."""
    selected = [spec for spec in specs if spec.export]
    if not selected:
        fail(f"CSV has no EXPORT=YES rows for {input_midi.name}")

    names: Set[str] = set()
    expected_file = input_midi.name.casefold()
    for spec in selected:
        if Path(spec.file).name.casefold() != expected_file:
            fail(
                f"internal selection error: CSV row {spec.row_number} FILE={spec.file!r} "
                f"does not match input MIDI {input_midi.name!r}"
            )
        if spec.name in names:
            fail(f"CSV row {spec.row_number}: duplicate NAME {spec.name} within {input_midi.name}")
        names.add(spec.name)
        if spec.slot_map not in slot_maps:
            fail(f"CSV row {spec.row_number}: unknown SLOT_MAP {spec.slot_map!r}")
        if spec.end_bar > len(bars):
            fail(
                f"CSV row {spec.row_number}: bar range {spec.start_bar}-{spec.end_bar} "
                f"exceeds MIDI bar count {len(bars)}"
            )
        start_bar = bars[spec.start_bar - 1]
        end_bar = bars[spec.end_bar - 1]
        actual_ts_values = {
            (bar.numerator, bar.denominator)
            for bar in bars[spec.start_bar - 1 : spec.end_bar]
        }
        csv_ts = parse_time_signature(spec.time_sig, row_number=spec.row_number)
        if len(actual_ts_values) != 1 or csv_ts not in actual_ts_values:
            actual_text = "→".join(
                f"{bar.numerator}/{bar.denominator}"
                for bar in bars[spec.start_bar - 1 : spec.end_bar]
            )
            fail(
                f"CSV row {spec.row_number}: TIME_SIG={spec.time_sig} does not match "
                f"bars {spec.start_bar}-{spec.end_bar} ({actual_text})"
            )
        expected_source = f"{input_midi.name}:{spec.start_bar}-{spec.end_bar}"
        source_core = spec.source.split(";", 1)[0].strip()
        if source_core != expected_source:
            fail(
                f"CSV row {spec.row_number}: SOURCE={spec.source!r}; "
                f"expected {expected_source!r}"
            )
        hits = drum_note_ons(events, start_bar.start_tick, end_bar.end_tick)
        if not hits:
            fail(
                f"CSV row {spec.row_number}: no CH10 drum note_on events "
                f"in selected range"
            )
        notes = {
            int(event.message.note)
            for event in hits
            if isinstance(event.message, Message)
        }
        missing = sorted(notes - slot_maps[spec.slot_map].accepted_notes)
        if missing:
            fail(
                f"CSV row {spec.row_number}: SLOT_MAP {spec.slot_map} "
                f"does not accept MIDI note(s) {missing}"
            )

    return selected


# ---------------------------------------------------------------------------
# MIDI splitting
# ---------------------------------------------------------------------------


def extract_segment_messages(
    events: Sequence[AbsoluteEvent],
    start_tick: int,
    end_tick: int,
) -> List[Tuple[int, int, Message | MetaMessage]]:
    segment: List[Tuple[int, int, Message | MetaMessage]] = []
    time_sig, tempo = active_meta_before(events, start_tick)
    segment.append((0, -20, MetaMessage("time_signature", numerator=time_sig[0], denominator=time_sig[1], time=0)))
    segment.append((0, -19, MetaMessage("set_tempo", tempo=tempo, time=0)))

    for event in events:
        if event.tick < start_tick:
            continue
        if event.tick >= end_tick:
            break
        msg = event.message
        relative = event.tick - start_tick
        if isinstance(msg, Message) and getattr(msg, "channel", -1) == 9 and msg.type in {"note_on", "note_off"}:
            segment.append((relative, event.order, msg.copy(time=0)))
        elif isinstance(msg, MetaMessage) and msg.type in {"set_tempo", "time_signature"}:
            if relative == 0:
                continue
            segment.append((relative, event.order, msg.copy(time=0)))

    # Guarantee note-offs for any notes still active at the segment boundary.
    active: Dict[int, int] = {}
    for tick, _, msg in sorted(segment, key=lambda item: (item[0], item[1])):
        if not isinstance(msg, Message) or getattr(msg, "channel", -1) != 9:
            continue
        if msg.type == "note_on" and msg.velocity > 0:
            active[msg.note] = active.get(msg.note, 0) + 1
        elif msg.type == "note_off" or (msg.type == "note_on" and msg.velocity == 0):
            if active.get(msg.note, 0) > 0:
                active[msg.note] -= 1
    close_tick = max(0, end_tick - start_tick - 1)
    order = 10**9
    for note, count in sorted(active.items()):
        for _ in range(count):
            segment.append((close_tick, order, Message("note_off", channel=9, note=note, velocity=0, time=0)))
            order += 1

    return sorted(segment, key=lambda item: (item[0], item[1]))


def save_segment_midi(
    spec: PatternSpec,
    output_path: Path,
    mid: MidiFile,
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
) -> None:
    start_tick = bars[spec.start_bar - 1].start_tick
    end_tick = bars[spec.end_bar - 1].end_tick
    messages = extract_segment_messages(events, start_tick, end_tick)

    out = MidiFile(type=0, ticks_per_beat=mid.ticks_per_beat)
    track = MidiTrack()
    out.tracks.append(track)

    last_tick = 0
    for absolute_tick, _, msg in messages:
        delta = absolute_tick - last_tick
        if delta < 0:
            fail(f"internal error while writing {spec.name}: negative delta time")
        last_tick = absolute_tick
        track.append(msg.copy(time=delta))
    segment_length = end_tick - start_tick
    track.append(MetaMessage("end_of_track", time=max(0, segment_length - last_tick)))
    out.save(output_path)



# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog=SCRIPT_NAME,
        description=(
            "Split EXPORT=YES drum-pattern ranges from one original MIDI file "
            "or from all CSV-referenced MIDI files in a directory."
        ),
        epilog=(
            "File mode processes only matching CSV rows. Directory mode processes "
            "all EXPORT=YES CSV rows and requires every referenced MIDI file to be "
            "present. Default behavior writes one NAME.MID per selected row; use "
            "--dry-run to validate and preview without creating files."
        ),
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Original MIDI file, or directory containing the original MIDI files",
    )
    parser.add_argument(
        "pattern_csv",
        type=Path,
        help="Reviewed ADC PatternLab CSV (a combined multi-file CSV is allowed)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory (default: <CSV directory>/split-midi)",
    )
    parser.add_argument(
        "--slot-maps",
        type=Path,
        default=None,
        help="Slot-map definition JSON (default: slot_map_definitions.json beside this script)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow existing NAME.MID output files to be overwritten",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and print the split plan without writing files",
    )
    parser.add_argument("--version", action="version", version=VERSION_TEXT)
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)

    if not args.pattern_csv.is_file():
        fail(f"CSV file not found: {args.pattern_csv}")
    if not args.input.exists():
        fail(f"input path not found: {args.input}")
    if not (args.input.is_file() or args.input.is_dir()):
        fail(f"input must be a MIDI file or directory: {args.input}")

    slot_map_path = args.slot_maps or Path(__file__).with_name("slot_map_definitions.json")
    slot_maps = load_slot_maps(slot_map_path)
    specs = load_pattern_csv(args.pattern_csv)
    export_specs = [spec for spec in specs if spec.export]
    if not export_specs:
        fail("CSV has no EXPORT=YES rows")

    # Resolve source MIDI files.
    if args.input.is_file():
        if args.input.suffix.lower() not in {".mid", ".midi"}:
            fail(f"input file is not a MIDI file: {args.input}")
        wanted = args.input.name.casefold()
        selected_specs = [
            spec for spec in export_specs
            if Path(spec.file).name.casefold() == wanted
        ]
        if not selected_specs:
            fail(
                f"CSV has no EXPORT=YES rows for input MIDI {args.input.name!r}"
            )
        midi_jobs = [(args.input, selected_specs)]
        mode = "file"
    else:
        # Case-insensitive basename lookup; .mid and .midi are both accepted.
        available: Dict[str, Path] = {}
        duplicates: Dict[str, List[Path]] = {}
        for path in sorted(args.input.iterdir()):
            if not path.is_file() or path.suffix.lower() not in {".mid", ".midi"}:
                continue
            key = path.name.casefold()
            if key in available:
                duplicates.setdefault(key, [available[key]]).append(path)
            else:
                available[key] = path

        if duplicates:
            key, paths = next(iter(duplicates.items()))
            fail(
                "directory contains MIDI filenames that differ only by case: "
                + ", ".join(str(p.name) for p in paths)
            )

        specs_by_file: Dict[str, List[PatternSpec]] = {}
        original_names: Dict[str, str] = {}
        for spec in export_specs:
            key = Path(spec.file).name.casefold()
            specs_by_file.setdefault(key, []).append(spec)
            original_names.setdefault(key, Path(spec.file).name)

        missing = [
            original_names[key]
            for key in specs_by_file
            if key not in available
        ]
        if missing:
            preview = ", ".join(sorted(missing)[:12])
            extra = len(missing) - min(len(missing), 12)
            suffix = f" (+{extra} more)" if extra else ""
            fail(
                f"directory is missing {len(missing)} MIDI file(s) referenced by "
                f"EXPORT=YES CSV rows: {preview}{suffix}"
            )

        midi_jobs = [
            (available[key], specs_by_file[key])
            for key in sorted(specs_by_file, key=lambda k: original_names[k].casefold())
        ]
        mode = "directory"

    # Global output names must remain unique because all split files share one
    # output directory.
    seen_names: Dict[str, PatternSpec] = {}
    for _midi_path, job_specs in midi_jobs:
        for spec in job_specs:
            key = spec.name.casefold()
            if key in seen_names:
                first = seen_names[key]
                fail(
                    f"duplicate output NAME {spec.name!r} in CSV rows "
                    f"{first.row_number} and {spec.row_number}"
                )
            seen_names[key] = spec

    output_dir = args.output_dir or args.pattern_csv.parent / "split-midi"

    print(VERSION_TEXT)
    print(f"[OK] mode       : {mode}")
    print(f"[OK] input      : {args.input}")
    print(f"[OK] CSV        : {args.pattern_csv}")
    print(f"[OK] SLOT_MAPS  : {slot_map_path}")
    print(f"[OK] MIDI files : {len(midi_jobs)}")
    print(f"[OK] export rows: {sum(len(job_specs) for _, job_specs in midi_jobs)}")
    print(f"[PLAN] split MIDI -> {output_dir}")

    prepared = []
    for midi_path, job_specs in midi_jobs:
        try:
            mid = MidiFile(str(midi_path))
        except Exception as exc:
            fail(f"cannot read MIDI {midi_path}: {exc}")
        if mid.type not in (0, 1):
            fail(f"{midi_path.name}: only SMF Type 0 or 1 is supported, got Type {mid.type}")

        events = merged_absolute_events(mid)
        total_tick = max((event.tick for event in events), default=0)
        bars = build_bar_map(
            mid.ticks_per_beat,
            collect_time_signatures(events),
            total_tick,
        )
        selected = validate_specs(job_specs, midi_path, slot_maps, bars, events)
        prepared.append((midi_path, mid, bars, events, selected))

        print(
            f"       {midi_path.name}: {len(selected)} pattern(s) "
            f"· Type {mid.type} · TPQ {mid.ticks_per_beat} · {len(bars)} bars"
        )
        for spec in selected:
            print(f"         {spec.name}.MID <- bars {spec.start_bar}-{spec.end_bar}")

    if args.dry_run:
        print("[DRY RUN] Validation completed; no files were written.")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    conflicts = [
        output_dir / f"{spec.name}.MID"
        for _, _, _, _, selected in prepared
        for spec in selected
        if (output_dir / f"{spec.name}.MID").exists()
    ]
    if conflicts and not args.overwrite:
        fail(
            f"split MIDI output already exists: {conflicts[0]} "
            f"(use --overwrite)"
        )

    split_count = 0
    for midi_path, mid, bars, events, selected in prepared:
        for spec in selected:
            output_path = output_dir / f"{spec.name}.MID"
            save_segment_midi(spec, output_path, mid, bars, events)
            split_count += 1
            print(
                f"[SPLIT] {output_path.name} <- "
                f"{midi_path.name} bars {spec.start_bar}-{spec.end_bar}"
            )

    print(f"[DONE] split MIDI: {split_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
